import { model } from "@medusajs/framework/utils"

/**
 * A real outgoing payment we made (or scheduled, when auto-generated by the
 * recurring-expenses cron). Each row "consumes" budget from its category's
 * bucket once status becomes "paid" — at that moment the wallet ledger
 * entry is written.
 */
const FinanzasExpense = model.define("finanzas_expense", {
  id: model.id().primaryKey(),
  category_id: model.text(),

  description: model.text(),
  amount_usdt: model.number(),
  amount_bs: model.number().nullable(),
  rate_bs_per_usdt: model.number().nullable(),
  paid_from_wallet_id: model.text().nullable(),

  receipt_url: model.text().nullable(),
  expense_date: model.dateTime(),
  notes: model.text().nullable(),

  // "paid" | "pending_payment"
  status: model.text().default("paid"),
  // "YYYY-MM" — set by recurring cron for idempotency
  auto_generated_for_month: model.text().nullable(),
})

export default FinanzasExpense
